<div class="py-4">
    <header class="jumbotron posts-hero text-center w3-round-xlarge"><h1 class="display-4 font-weight-bold">Privacy &amp; community policy</h1><p class="lead">Understand what you share and how this application works.</p><p class="small mb-0">Last updated: <time datetime="2026-10-06">October 6, 2026</time></p></header>
    <article class="card w3-round-xlarge"><div class="card-body p-4 p-md-5">
        <h2 class="h4">Account information</h2><p>We store the name, username, email address, and hashed password used for your account, together with account status and creation dates. This information supports sign-in and account management. You can update your name, email, and password in account settings.</p>
        <h2 class="h4 mt-4">No sale of personal information</h2><p>We do not sell your personal information to third parties for any reason.</p>
        <h2 class="h4 mt-4">Articles, products, and events</h2><p>Published articles and product listings are public. Product listings may identify the contributor. Images uploaded for products are stored in publicly accessible storage, so do not upload private images. Draft articles, draft product details, and personal calendar events are managed through your signed-in account. Do not put confidential information into public content.</p>
        <h2 class="h4 mt-4">Sessions and external services</h2><p>The application uses session cookies and security tokens to maintain sign-in and protect forms. A remember-me option can keep you signed in. Our pages load styling, icons, and scripts from external providers, whose servers receive connection information such as your IP address. Following an external link takes you to a service with its own privacy practices.</p>
        <h2 class="h4 mt-4" id="advertising">Advertising and Google cookies</h2>
        <p>Brotherfall may use Google AdSense to support its public content. Where Google ads are enabled, Google and other advertising providers may use cookies based on your previous visits to Brotherfall and other websites. These cookies allow Google and its partners to personalize the ads you see. Other participating ad networks may also use their own cookies.</p>
        <p>Learn how Google handles information from partner websites in <a href="https://policies.google.com/technologies/partner-sites">Google's partner-site privacy information</a>.</p>
        <h2 class="h4 mt-4" id="advertising-choices">Your advertising choices</h2>
        <p>You can manage or turn off Google ad personalization through <a href="https://myadcenter.google.com/">Google My Ad Center</a>. For participating third-party advertisers, visit <a href="https://www.aboutads.info/choices/">YourAdChoices</a> to explore opt-out options. Opting out of personalization does not necessarily remove advertising.</p>
        <p>You can also block or delete cookies in your browser. Blocking session cookies may prevent sign-in or other account features from working.</p>
        <h2 class="h4 mt-4" id="advertising-consent">Consent for advertising</h2>
        <p>Before enabling personalized Google ads for visitors in the European Economic Area, the United Kingdom or Switzerland, we will implement a Google-certified consent management platform. Where a consent message is displayed, use its controls to review advertising partners and choose whether to consent. Any available privacy-settings control will allow you to revisit those choices. This policy is information about our practices, not a request for or record of your consent.</p>
        <h2 class="h4 mt-4">Affiliate links</h2><p>Some product links are affiliate links. The contributor may receive a commission if you purchase through them. We count visits through product links. Purchases, payments, shipping, returns, and product availability are handled by the external seller; verify current prices and terms on their website.</p>
        <h2 class="h4 mt-4">Contact messages and records</h2><p>Contact forms send your name, email, subject, and message to our support mailbox so we can respond. Hosting and application logs may contain technical request and error information. Deleted articles, products, and events may remain in stored records or backups rather than being immediately erased.</p>
        <h2 class="h4 mt-4">Application ratings</h2><p>When you submit a rating, we store your score, optional feedback, IP address, and submission date. Ratings from signed-in members are linked to their account. Administrators can review these records to improve the application and investigate abuse.</p>
        <h2 class="h4 mt-4">Responsible use</h2><p>Publish only content you have permission to share. Do not post deceptive offers, unlawful material, harassment, or someone else's private information. Clearly disclose commercial relationships. Report problematic content with a link through our contact page.</p>
        <h2 class="h4 mt-4">Business service requests</h2><p>When you request a website audit or sponsored placement, we store your name, email, website address, and brief so admins can respond and manage the work. Quotes, payment references, reports, and order history are retained for service administration. Payments are arranged separately; this application does not collect card details. Audit reports are accessible to anyone holding their private, expiring report link. Approved sponsor names, copy, and links are public during the agreed placement period and are labeled Sponsored.</p>
        <h2 class="h4 mt-4">Questions and data requests</h2><p>For questions about your information, corrections, or removal requests, @guest <a wire:navigate href="{{ route('pages.contact') }}">contact support</a> @else contact support @endguest. We may need to verify account ownership before processing a request.</p>
    </div></article>
</div>
