<div class="py-4">
    <header class="jumbotron posts-hero text-center w3-round-xlarge"><h1 class="display-4 font-weight-bold">Privacy &amp; community policy</h1><p class="lead">Understand what you share and how this application works.</p></header>
    <article class="card w3-round-xlarge"><div class="card-body p-4 p-md-5">
        <h2 class="h4">Account information</h2><p>We store the name, username, email address, and hashed password used for your account, together with account status and creation dates. This information supports sign-in and account management. You can update your name, email, and password in account settings.</p>
        <h2 class="h4 mt-4">Articles, products, and events</h2><p>Published articles and product listings are public. Product listings may identify the contributor. Images uploaded for products are stored in publicly accessible storage, so do not upload private images. Draft articles, draft product details, and personal calendar events are managed through your signed-in account. Do not put confidential information into public content.</p>
        <h2 class="h4 mt-4">Sessions and external services</h2><p>The application uses session cookies and security tokens to maintain sign-in and protect forms. A remember-me option can keep you signed in. Our pages load styling, icons, and scripts from external providers, whose servers receive connection information such as your IP address. Following an external link takes you to a service with its own privacy practices.</p>
        <h2 class="h4 mt-4">Affiliate links</h2><p>Some product links are affiliate links. The contributor may receive a commission if you purchase through them. We count visits through product links. Purchases, payments, shipping, returns, and product availability are handled by the external seller; verify current prices and terms on their website.</p>
        <h2 class="h4 mt-4">Contact messages and records</h2><p>Contact forms send your name, email, subject, and message to our support mailbox so we can respond. Hosting and application logs may contain technical request and error information. Deleted articles, products, and events may remain in stored records or backups rather than being immediately erased.</p>
        <h2 class="h4 mt-4">Application ratings</h2><p>When you submit a rating, we store your score, optional feedback, IP address, and submission date. Ratings from signed-in members are linked to their account. Administrators can review these records to improve the application and investigate abuse.</p>
        <h2 class="h4 mt-4">Responsible use</h2><p>Publish only content you have permission to share. Do not post deceptive offers, unlawful material, harassment, or someone else's private information. Clearly disclose commercial relationships. Report problematic content with a link through our contact page.</p>
        <h2 class="h4 mt-4">Business service requests</h2><p>When you request a website audit or sponsored placement, we store your name, email, website address, and brief so admins can respond and manage the work. Quotes, payment references, reports, and order history are retained for service administration. Payments are arranged separately; this application does not collect card details. Audit reports are accessible to anyone holding their private, expiring report link. Approved sponsor names, copy, and links are public during the agreed placement period and are labeled Sponsored.</p>
        <h2 class="h4 mt-4">Questions and data requests</h2><p>For questions about your information, corrections, or removal requests, @guest <a wire:navigate href="{{ route('pages.contact') }}">contact support</a> @else contact support @endguest. We may need to verify account ownership before processing a request.</p>
    </div></article>
</div>
