<div class="py-4">
    <header class="admin-welcome p-4 mb-4"><p class="small text-uppercase font-weight-bold">Administration</p><h1 class="h3">Content rewards</h1><p class="mb-0">Fund and award eligible community contributions.</p></header>
    @if (session('rewardStatus'))<div class="alert alert-success" role="status">{{ session('rewardStatus') }}</div>@endif
    @error('reward')<div class="alert alert-warning" role="alert">{{ $message }}</div>@enderror
    <div class="row mb-4">
        <div class="col-md-5 mb-3"><section class="dashboard-panel p-4 h-100"><p class="small text-uppercase text-muted">Available fund</p><p class="display-4">${{ number_format($fund->balance_cents / 100, 2) }}</p><form wire:submit="depositFunds"><label for="reward-deposit">Add funds (USD)</label><div class="input-group"><div class="input-group-prepend"><span class="input-group-text">$</span></div><input id="reward-deposit" type="number" min="0.01" max="1000000" step="0.01" class="form-control @error('deposit') is-invalid @enderror" wire:model="deposit" required><div class="input-group-append"><button class="btn btn-primary" wire:loading.attr="disabled">Add funds</button></div></div>@error('deposit')<p class="text-danger small mt-2">{{ $message }}</p>@enderror</form></section></div>
        <div class="col-md-7 mb-3"><section class="dashboard-panel p-4 h-100"><h2 class="h5">Reward rules</h2><ul class="mb-0"><li>${{ number_format($fund->quote_reward_cents / 100, 2) }} for an account-linked quote</li><li>${{ number_format($fund->post_reward_cents / 100, 2) }} for a published {{ $fund->post_min_words }}–{{ $fund->post_max_words }} word post in any selected category</li><li>Each quote or post can be rewarded once</li><li>Rewards are recorded in the ledger below</li></ul></section></div>
    </div>
    <div class="row">
        <div class="col-lg-6 mb-4"><section class="dashboard-panel p-4"><h2 class="h5">Eligible quotes</h2>@forelse ($quotes as $quote)<div class="border-top py-3" wire:key="reward-quote-{{ $quote->id }}"><p class="mb-1">{{ Str::limit($quote->content, 140) }}</p><small class="text-muted">{{ $quote->user->name }}</small><button class="btn btn-success btn-sm float-right" wire:click="award('quote', {{ $quote->id }})" wire:confirm="Award ${{ number_format($fund->quote_reward_cents / 100, 2) }} for this quote?" wire:loading.attr="disabled">Award ${{ number_format($fund->quote_reward_cents / 100, 2) }}</button></div>@empty<p class="text-muted mb-0">No eligible quotes.</p>@endforelse</section></div>
        <div class="col-lg-6 mb-4"><section class="dashboard-panel p-4"><h2 class="h5">Eligible posts</h2>@forelse ($posts as $post)<div class="border-top py-3" wire:key="reward-post-{{ $post->id }}"><p class="mb-1">{{ $post->title }}</p><small class="text-muted">{{ $post->author?->name ?? 'Deleted account' }} · {{ $post->reward_word_count }} words · {{ $post->category }}</small><button class="btn btn-success btn-sm float-right" wire:click="award('post', {{ $post->id }})" wire:confirm="Award ${{ number_format($fund->post_reward_cents / 100, 2) }} for this post?" wire:loading.attr="disabled">Award ${{ number_format($fund->post_reward_cents / 100, 2) }}</button></div>@empty<p class="text-muted mb-0">No eligible posts.</p>@endforelse</section></div>
    </div>
    <section class="dashboard-panel p-4"><h2 class="h5">Recent reward ledger</h2><div class="table-responsive"><table class="table"><thead><tr><th>Recipient</th><th>Content</th><th>Amount</th><th>Awarded by</th><th>Date</th></tr></thead><tbody>@forelse ($recentRewards as $reward)<tr><td>{{ $reward->user->name }}</td><td>{{ ucfirst($reward->content_type) }} #{{ $reward->content_id }}</td><td>${{ number_format($reward->amount_cents / 100, 2) }}</td><td>{{ $reward->awardedBy->name }}</td><td>{{ $reward->created_at->format('M j, Y') }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No rewards awarded yet.</td></tr>@endforelse</tbody></table></div></section>
</div>
